### ISSUE TITLE
看了框架介绍，少了切入思想

### ISSUE THREAD

**Issue by queryDuan** [ueaner/soliphp#1]
代码没来得及看，只看了介绍，感觉少了面向切面的思想，比如有些东西，并不属于任何一个模型，但是是任何模型都可能拿来复用的算法之类的，Yii里面是通过behaviors实现的。

**Comment by ueaner** [comment]
感谢反馈！
1. 依赖注入容器中提供的服务和事件管理器中提供的事件，都是在做切面；
2. 模型部分依据实际的应用场景，方便进行扩展，Soli 只提供了常用的操作方法；
3. Yii 的 behaviors 没怎么用过不做评论；使用 PHP Trait 特性＋适当的组合继承是不是可以满足你这方面的需求呢，如无法满足，烦请指出。

再次感谢，🙏！
